owner: shadowdara
repo: upptime

sites:
  - name: samengine
    url: https://samengine.vercel.app/

  - name: samengine js
    url: https://samengine.js.org/

  - name: l1nx
    url: https://l1nx-one.vercel.app/

  - name: blog
    url: https://shadowdara.wordpress.com/

  - name: Zug fahren
    url: https://zug-fahren.vercel.app/

  - name: GH Page
    url: https://shadowdara.github.io/

  - name: Ninjagonator
    url: https://ninjagonator.ju.mp/

  - name: Ninjagonator Static
    url: https://ninjagonator.netlify.app/
    
  - name: Shadowdara - Vercel
    url: https://shadowdara.vercel.app/
    
  - name: Minecrafttools
    url: https://minecrafttools.vercel.app/
    
  - name: Repo Database Creator - Vercel
    url: https://repo-database-creator.vercel.app/
    
  - name: Shadowdara - Infinityfree
    url: https://shadowdara.42web.io/
    
  - name: no fucking CORS - Vercel
    url: https://no-fucking-cors.vercel.app/
    
  - name: Watch Nexo Knights
    url: https://watchnexoknights.vercel.app/
    
  - name: Zug fahren
    url: https://zug-fahren.rf.gd/

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Shadowdara / Upptime
  introTitle: "The **Status Page** for Shadowdara's projects!"
  introMessage: This Website contains my projects websites and shows a history of their down- and response-times.
  navbar:
    - title: Status
      href: /$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
