owner: shadowdara
repo: upptime

sites:
  - name: Shadowdara - Vercel
    url: https://shadowdara.vercel.app/
  - name: Repo Database Creator - Vercel
    url: https://repo-database-creator.vercel.app/
  - name: Shadowdara - Infinityfree
    url: https://shadowdara.42web.io/
  - name: no fucking CORS - Vercel
    url: https://no-fucking-cors.vercel.app/
  - name: Watch Nexo Knights
    url: https://watchnexoknights.vercel.app/
  - name: Zug fahren
    url: https://zug-fahren.rf.gd/
  - name: Zug fahren tmp
    url: https://zug-fahren-tp.vercel.app/

status-website:
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Shadowdara / Upptime
  introTitle: "The **Status Page** for Shadowdara's projects!"
  introMessage: This Website contains my projects websites and shows a history of their down- and response-times.
  navbar:
    - title: Status
      href: /$REPO
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
